In [126]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split, TensorDataset


In [127]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(1,1)
  def forward(self,x):
    x = self.fc1(x)
    return x



In [128]:
with torch.no_grad():
  input = torch.tensor([30.])
  output = mynet(input)
  print(output)

tensor([30.7426])


In [129]:
class MyDataset(Dataset):
  def __init__(self, x_data, y_data):
    self.x_data = x_data
    self.y_data = y_data

  def __len__(self):
    return len(self.x_data)

  def __getitem__(self,idx):
    return self.x_data[idx],self.y_data[idx]

In [148]:
x_data = torch.tensor(range(100)).float()
y_data = torch.tensor(range(100)).float()

dataset = MyDataset(x_data, y_data)
train_dataset, test_dataset = random_split(dataset, [80,20])

trainloader = DataLoader(train_dataset, batch_size = 1, shuffle = True)
testloader = DataLoader(test_dataset, batch_size = 1, shuffle = True)

In [149]:
# Input epoch num
num_epoch = 100

mynet = Net()

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(mynet.parameters(), lr = 0.0001)

counter = 0
for epoch in range(100):
  for inputs, targets in trainloader:

    optimizer.zero_grad()
    outputs = mynet(inputs)
    loss = criterion(outputs, targets)
    loss.backward()
    optimizer.step()
  if counter %10 == 0:
    print("epoch = ",epoch," , loss = ",loss)
  counter += 1

epoch =  0  , loss =  tensor(0.0814, grad_fn=<MseLossBackward0>)
epoch =  10  , loss =  tensor(0.0026, grad_fn=<MseLossBackward0>)
epoch =  20  , loss =  tensor(8.5384e-06, grad_fn=<MseLossBackward0>)
epoch =  30  , loss =  tensor(0.0378, grad_fn=<MseLossBackward0>)
epoch =  40  , loss =  tensor(0.0140, grad_fn=<MseLossBackward0>)
epoch =  50  , loss =  tensor(0.0227, grad_fn=<MseLossBackward0>)
epoch =  60  , loss =  tensor(0.0326, grad_fn=<MseLossBackward0>)
epoch =  70  , loss =  tensor(0.0471, grad_fn=<MseLossBackward0>)
epoch =  80  , loss =  tensor(0.0295, grad_fn=<MseLossBackward0>)
epoch =  90  , loss =  tensor(0.0049, grad_fn=<MseLossBackward0>)


In [150]:
mynet.eval()

correct = 0
total = 0

with torch.no_grad():
  for x, y in testloader:
    pred_y = mynet(x)
    print("("+str(x)+","+str(y)+") : "+str(pred_y))




(tensor([59.]),tensor([59.])) : tensor([59.0099])
(tensor([38.]),tensor([38.])) : tensor([38.0778])
(tensor([92.]),tensor([92.])) : tensor([91.9030])
(tensor([12.]),tensor([12.])) : tensor([12.1620])
(tensor([18.]),tensor([18.])) : tensor([18.1426])
(tensor([72.]),tensor([72.])) : tensor([71.9678])
(tensor([40.]),tensor([40.])) : tensor([40.0713])
(tensor([88.]),tensor([88.])) : tensor([87.9160])
(tensor([79.]),tensor([79.])) : tensor([78.9451])
(tensor([30.]),tensor([30.])) : tensor([30.1037])
(tensor([0.]),tensor([0.])) : tensor([0.2008])
(tensor([28.]),tensor([28.])) : tensor([28.1102])
(tensor([81.]),tensor([81.])) : tensor([80.9386])
(tensor([52.]),tensor([52.])) : tensor([52.0325])
(tensor([76.]),tensor([76.])) : tensor([75.9548])
(tensor([77.]),tensor([77.])) : tensor([76.9516])
(tensor([80.]),tensor([80.])) : tensor([79.9419])
(tensor([86.]),tensor([86.])) : tensor([85.9225])
(tensor([27.]),tensor([27.])) : tensor([27.1134])
(tensor([16.]),tensor([16.])) : tensor([16.1490])


In [152]:
mynet.eval()
with torch.no_grad():
  print(mynet(torch.tensor([11.4])))

tensor([11.5639])
